### PR TITLE
FIX: Make sure magazine size is always an even number.

### PR DESCRIPTION
**Pull request by surmiran**

### CODE REVIEW

**Review by phg49389 — DISMISSED** [review]
The Subata Explosive Reload OC rounds down; change to Math.floor()?

**Comment by chaseconey** [comment]
Wouldn't we want to just round these? Confused why we are using `floor` and `ceil`?

**Comment by Darthmaul** [comment]
We keep getting complaints about this. If we can close out the Tailwind PR today I will try to finish this also.

**Review by Darthmaul — APPROVED** [review]
We will push and if any issues revert this

**Pull request merged**
